"""개발/비개발 직무 시드 데이터

기존 LLM 프롬프트(job.py, job_worker.py)에 명시된 예시를 기반으로 확장.
Milvus job_roles 컬렉션에 초기 로드하여 직무 필터링에 사용한다.
"""

# 개발 관련 직무/부서명
DEV_ROLES = [
    # ── 직무 (한국어) ──
    "백엔드 개발자",
    "프론트엔드 개발자",
    "풀스택 개발자",
    "서버 개발자",
    "웹 개발자",
    "모바일 개발자",
    "iOS 개발자",
    "Android 개발자",
    "데이터 엔지니어",
    "데이터 분석가",
    "데이터 사이언티스트",
    "데이터 애널리스트",
    "데이터 플랫폼 엔지니어",
    "데이터 제품 매니저",
    "ML 엔지니어",
    "AI 엔지니어",
    "머신러닝 엔지니어",
    "딥러닝 엔지니어",
    "NLP 엔지니어",
    "컴퓨터비전 엔지니어",
    "MLOps 엔지니어",
    "DevOps 엔지니어",
    "SRE 엔지니어",
    "인프라 엔지니어",
    "클라우드 엔지니어",
    "클라우드 플랫폼 엔지니어",
    "보안 엔지니어",
    "QA 엔지니어",
    "테스트 엔지니어",
    "임베디드 개발자",
    "시스템 엔지니어",
    "네트워크 엔지니어",
    "DBA",
    "블록체인 개발자",
    "게임 개발자",
    "게임 클라이언트 개발자",
    "게임 서버 개발자",
    "로봇 소프트웨어 엔지니어",
    "센서퓨전 소프트웨어 엔지니어",
    "물류 알고리즘 엔지니어",
    "시뮬레이션 엔지니어",
    "IIoT 플랫폼 엔지니어",
    "OT·IT 통합 엔지니어",
    "추천 시스템 엔지니어",
    "RAG 시스템 엔지니어",
    "RPA 개발자",
    "사내 툴 개발자",
    "사내 도구 엔지니어",
    "백오피스 개발자",
    "내부 시스템 개발자",
    "업무자동화 웹서비스 개발자",
    "워크플로우 자동화 엔지니어",
    "슬랙 봇 개발자",
    "슬랙 앱·봇 개발자",
    "그룹웨어·인트라넷 개발자",
    "통합 검색 플랫폼 개발자",
    "빌드·배포 파이프라인 엔지니어",
    "개발환경 자동화 엔지니어",
    "성능·자동화 엔지니어",
    "클라우드 비용 관리 엔지니어",
    "데이터 거버넌스 엔지니어",
    "AI 정책·모델 리스크 엔지니어",
    "HR 데이터 엔지니어",
    "HR 시스템 개발자",
    "HR 플랫폼 엔지니어",
    "HR 애널리틱스 엔지니어",
    "조직문화 데이터 분석가",
    "직원 경험 플랫폼 엔지니어",
    # ── 직무 (영어) ──
    "Backend Engineer",
    "Backend Developer",
    "Frontend Engineer",
    "Frontend Developer",
    "Full Stack Engineer",
    "Full Stack Developer",
    "Software Engineer",
    "Software Developer",
    "Site Reliability Engineer",
    "DevOps Engineer",
    "Data Engineer",
    "Data Scientist",
    "Data Analyst",
    "Machine Learning Engineer",
    "ML Engineer",
    "AI Engineer",
    "Deep Learning Engineer",
    "NLP Engineer",
    "Computer Vision Engineer",
    "MLOps Engineer",
    "Platform Engineer",
    "Cloud Engineer",
    "Cloud Architect",
    "Security Engineer",
    "Cybersecurity Engineer",
    "QA Engineer",
    "Test Engineer",
    "SDET",
    "Mobile Developer",
    "Mobile Engineer",
    "iOS Engineer",
    "Android Engineer",
    "Embedded Engineer",
    "Embedded Developer",
    "Firmware Engineer",
    "Systems Engineer",
    "Network Engineer",
    "Database Administrator",
    "Infrastructure Engineer",
    "Blockchain Developer",
    "Blockchain Engineer",
    "Game Developer",
    "Game Programmer",
    "Observability Engineer",
    "Reliability Engineer",
    "Solutions Architect",
    "Technical Lead",
    "Tech Lead",
    "Engineering Manager",
    "VP of Engineering",
    "CTO",
    "Chief Technology Officer",
    "Principal Engineer",
    "Staff Engineer",
    "Senior Engineer",
    "Software Architect",
    "System Architect",
    "Release Engineer",
    "Build Engineer",
    "CI/CD Engineer",
    "Automation Engineer",
    "Performance Engineer",
    "Data Platform Engineer",
    "Analytics Engineer",
    "ETL Developer",
    "BI Engineer",
    "Integration Engineer",
    "API Developer",
    "Microservices Engineer",
    "Kubernetes Engineer",
    "Container Engineer",
    "Edge Computing Engineer",
    "IoT Engineer",
    "Robotics Engineer",
    "AR/VR Developer",
    "Graphics Engineer",
    "Compiler Engineer",
    "Low-Level Systems Engineer",
    # ── 부서명 (한국어 기본) ──
    "개발팀",
    "플랫폼팀",
    "인프라팀",
    "데이터팀",
    "AI팀",
    "엔지니어링팀",
    "옵저버빌리티팀",
    "서비스개발팀",
    "백엔드팀",
    "프론트엔드팀",
    "모바일팀",
    "보안팀",
    "QA팀",
    "SRE팀",
    "DevOps팀",
    "클라우드팀",
    "시스템팀",
    "기술팀",
    "R&D",
    "연구개발팀",
    "CTO실",
    "기술본부",
    "개발조직",
    # ── 부서명 (DX·DT·AI 조직) ──
    "DX 혁신센터",
    "DX 전략팀",
    "DX 조직",
    "DT센터",
    "디지털혁신실",
    "AI랩",
    "AI센터",
    "AI 전략실",
    "AI 생산성 혁신 그룹",
    "AI 업무혁신 TF",
    "AX 조직",
    "자율주행 AI랩",
    "데이터랩",
    "모빌리티 데이터랩",
    "스마트팩토리 추진단",
    "스마트팩토리 DX 조직",
    # ── 부서명 (챕터·사일로·스쿼드) ──
    "프론트엔드 챕터",
    "서버 챕터",
    "모바일 챕터",
    "인터널 사일로 팀",
    # ── 부서명 (내부 플랫폼·DX·생산성) ──
    "협업플랫폼팀",
    "워크플로우혁신 조직",
    # ── 부서명 (영어) ──
    "Engineering",
    "Engineering Team",
    "Platform",
    "Platform Team",
    "Infrastructure",
    "Infrastructure Team",
    "Development",
    "Development Team",
    "Backend Team",
    "Frontend Team",
    "Mobile Team",
    "Data Team",
    "Data Engineering",
    "AI Team",
    "AI Lab",
    "ML Team",
    "Machine Learning Team",
    "Security Team",
    "Cybersecurity Team",
    "QA Team",
    "Quality Assurance",
    "SRE Team",
    "DevOps Team",
    "Cloud Team",
    "Systems Team",
    "Network Team",
    "Database Team",
    "R&D Team",
    "Research and Development",
    "CTO Office",
    "Internal Platform Team",
    "Internal Developer Platform",
    "Developer Experience",
    "Developer Experience Team",
    "Platform Engineering",
    "Productivity Engineering",
    "Internal Tools",
    "Internal Tools Team",
    "Innovation Center",
    "Innovation Lab",
    "Smart Office",
    "Cloud Governance",
    "Data Governance",
    "AI Governance",
    "Logistics DX Lab",
    "Analytics Center of Excellence",
    "Cloud Center of Excellence",
    "Digital Strategy Office",
    "AI Strategy Office",
    "Site Reliability",
    "Release Engineering",
    "Build and Release",
    "Architecture Team",
    "Solutions Architecture",
    "Core Engineering",
    "Growth Engineering",
    "Product Engineering",
    "Search Team",
    "Search Engineering",
    "Payments Engineering",
    "Commerce Engineering",
    "Ads Engineering",
    "Trust and Safety Engineering",
    "Fraud Engineering",
    "Identity Team",
    "Auth Team",
    "API Team",
    "Tooling Team",
    "Observability Team",
    "Reliability Team",
    "Performance Team",
    "Edge Computing Team",
    "IoT Team",
    "Robotics Team",
    "Embedded Systems Team",
    "Firmware Team",
    "Computer Vision Team",
    "NLP Team",
    "Applied AI Team",
    "Applied ML Team",
    "MLOps Team",
    "Data Platform",
    "Data Platform Team",
    "Analytics Team",
    "BI Team",
    "Business Intelligence Engineering",
    "ETL Team",
    "Data Pipeline Team",
]

# 비개발 관련 직무/부서명 — 실제 존재하는 비즈니스 직무·부서
NON_DEV_ROLES = [
    # ── 비즈니스 직무 (기본) ──
    "마케팅",
    "마케팅 매니저",
    "영업",
    "영업 관리자",
    "인사",
    "인사 담당자",
    "총무",
    "경영지원",
    "회계",
    "재무",
    "법무",
    "홍보",
    "PR",
    "HR",
    "Finance",
    "Sales",
    "Marketing",
    # ── 비즈니스 직무 (실무 세부) ──
    "경영기획 담당자",
    "전략기획 담당자",
    "교육기획 담당자",
    "구매담당자",
    "구매 바이어",
    "물류기획 담당자",
    "물류운영 매니저",
    "재무분석가",
    "재무기획 담당자",
    "브랜드 매니저",
    "품질관리 담당자",
    "품질보증 담당자",
    "생산관리 담당자",
    "생산계획 담당자",
    "설비보전 담당자",
    "채용담당자",
    "채용 브랜딩 담당자",
    "보상·평가 담당자",
    "조직문화 담당자",
    "인재육성 담당자",
    "인사운영 담당자",
    "HRBP",
    "HR 기획 담당자",
    "HR 제도 담당자",
    "교육 프로그램 매니저",
    "광고·프로모션 담당자",
    "프로모션 담당자",
    "캠페인 플래너",
    "퍼포먼스 마케터",
    "카테고리 마케터",
    "영업사원",
    "영업지원 담당자",
    "B2B 영업담당자",
    "채널영업 담당자",
    "바이어",
    "셀러매니저",
    "고객성공 매니저",
    "CS 매니저",
    "사업개발 매니저",
    "운영 매니저",
    "점장",
    "점포운영 매니저",
    "수요예측 담당자",
    "성과관리 담당자",
    "복리후생 담당자",
    "사내 커뮤니케이션 담당자",
    "홍보담당자",
    "서비스기획 매니저",
    "상품기획 매니저",
    "객실승무원",
    "운항관리 직원",
    # ── 비즈니스 부서 (기본) ──
    "마케팅팀",
    "영업팀",
    "인사팀",
    "총무팀",
    "경영지원팀",
    "회계팀",
    "재무팀",
    "법무팀",
    "홍보팀",
    "고객지원팀",
    "CS팀",
    # ── 비즈니스 부서 (실무 세부) ──
    "경영기획팀",
    "경영전략팀",
    "전략기획팀",
    "교육팀",
    "교육개발팀",
    "구매팀",
    "국내영업팀",
    "해외영업팀",
    "글로벌마케팅팀",
    "브랜드마케팅팀",
    "브랜드전략팀",
    "브랜드팀",
    "품질관리팀",
    "품질보증팀",
    "생산관리팀",
    "설비관리팀",
    "물류팀",
    "서비스기획팀",
    "상품기획팀",
    "인사기획팀",
    "인사운영팀",
    "인재개발팀",
    "인재육성팀",
    "인사문화실",
    "인재전략팀",
    "피플앤컬처팀",
    "피플팀",
    "성장관리팀",
    "탤런트팀",
    "직원경험팀",
    "재무기획팀",
    "재경팀",
    "재무실",
    "재무부",
    "인사부",
    "SCM팀",
    "고객서비스팀",
    "고객성공팀",
    "셀러운영팀",
    "풀필먼트운영팀",
    "점포운영팀",
    "사업개발팀",
    "운영팀",
    "PR팀",
    "리테일마케팅팀",
    # ── 비즈니스 부서 (본부·실) ──
    "마케팅본부",
    "글로벌마케팅본부",
    "국내영업본부",
    "해외영업본부",
    "영업본부",
    "생산본부",
    "상품본부",
    "마케팅실",
    "국내영업실",
    "승무본부",
    "여객마케팅부",
    "화물영업부",
    "여객영업본부",
    "운항관리부",
    "마케팅부문",
]

# 직무/부서와 무관한 장난값·노이즈 — 어디에 입력되든 무조건 차단
IRRELEVANT_ROLES = [
    # 무관 직업
    "축구선수",
    "축구",
    "농구선수",
    "농구",
    "야구선수",
    "야구",
    "요리사",
    "요리",
    "음악가",
    "음악",
    "미술가",
    "미술",
    "간호사",
    "의사",
    "변호사",
    "교사",
    "선생님",
    "경찰관",
    "소방관",
    # 무관 단어
    "사과",
    "바나나",
    "청포도",
    "수박",
    "딸기",
    "건물주",
]
